// <auto-generated />
using System;
using FinanZen.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanZen.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250711200747_AddFamiliaSupport")]
    partial class AddFamiliaSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanZen.Server.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("tipo");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("CategoriaID")
                        .HasName("pk_categorias");

                    b.HasIndex("UsuarioID")
                        .HasDatabaseName("ix_categorias_usuario_id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("FinanZen.Server.Models.Familia", b =>
                {
                    b.Property<int>("FamiliaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("familia_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FamiliaId"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("FamiliaId")
                        .HasName("pk_familias");

                    b.ToTable("familias", (string)null);
                });

            modelBuilder.Entity("FinanZen.Server.Models.Orcamento", b =>
                {
                    b.Property<int>("OrcamentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orcamento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrcamentoID"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer")
                        .HasColumnName("familia_id");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("OrcamentoID")
                        .HasName("pk_orcamentos");

                    b.HasIndex("CategoriaID")
                        .HasDatabaseName("ix_orcamentos_categoria_id");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_orcamentos_familia_id");

                    b.HasIndex("UsuarioID")
                        .HasDatabaseName("ix_orcamentos_usuario_id");

                    b.ToTable("orcamentos", (string)null);
                });

            modelBuilder.Entity("FinanZen.Server.Models.Transacao", b =>
                {
                    b.Property<int>("TransacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transacao_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransacaoID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer")
                        .HasColumnName("familia_id");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("TransacaoID")
                        .HasName("pk_transacoes");

                    b.HasIndex("CategoriaID")
                        .HasDatabaseName("ix_transacoes_categoria_id");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_transacoes_familia_id");

                    b.HasIndex("UsuarioID")
                        .HasDatabaseName("ix_transacoes_usuario_id");

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("FinanZen.Server.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioID"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer")
                        .HasColumnName("familia_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("UsuarioID")
                        .HasName("pk_usuarios");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_usuarios_familia_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FinanZen.Server.Models.Categoria", b =>
                {
                    b.HasOne("FinanZen.Server.Models.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioID")
                        .HasConstraintName("fk_categorias_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanZen.Server.Models.Orcamento", b =>
                {
                    b.HasOne("FinanZen.Server.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamentos_categorias_categoria_id");

                    b.HasOne("FinanZen.Server.Models.Familia", "Familia")
                        .WithMany("Orcamentos")
                        .HasForeignKey("FamiliaId")
                        .HasConstraintName("fk_orcamentos_familias_familia_id");

                    b.HasOne("FinanZen.Server.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamentos_usuarios_usuario_id");

                    b.Navigation("Categoria");

                    b.Navigation("Familia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanZen.Server.Models.Transacao", b =>
                {
                    b.HasOne("FinanZen.Server.Models.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transacoes_categorias_categoria_id");

                    b.HasOne("FinanZen.Server.Models.Familia", "Familia")
                        .WithMany("Transacoes")
                        .HasForeignKey("FamiliaId")
                        .HasConstraintName("fk_transacoes_familias_familia_id");

                    b.HasOne("FinanZen.Server.Models.Usuario", "Usuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transacoes_usuarios_usuario_id");

                    b.Navigation("Categoria");

                    b.Navigation("Familia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanZen.Server.Models.Usuario", b =>
                {
                    b.HasOne("FinanZen.Server.Models.Familia", "Familia")
                        .WithMany("Usuarios")
                        .HasForeignKey("FamiliaId")
                        .HasConstraintName("fk_usuarios_familias_familia_id");

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("FinanZen.Server.Models.Categoria", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanZen.Server.Models.Familia", b =>
                {
                    b.Navigation("Orcamentos");

                    b.Navigation("Transacoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FinanZen.Server.Models.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
